SRCS	=	*.c ../get_next_line/*.c

HEADERS	= 	../libft/libft.a so_long.h ../get_next_line/get_next_line.h

CC		= 	clang -Wall -Wextra -Werror -D BUFFER_SIZE=5000

all	:
			$(CC) $(SRCS) $(HEADERS)
			@echo "Files compiled, run ./a.out to test output"
